#!/bin/bash

. ./functions

PATTERN=`flatListFilesFrom $1`

# TODO Call fgrep with the list previously created and another direcory name
# and print a list of filenames that were not found in the files contained in
# the directory, recursively

echo "$PATTERN"
