#!/bin/sh
# TODO Look for more interesting interpreter directives here: https://en.wikipedia.org/wiki/Shebang_(Unix)

# TODO Accept a directory name and call a function that returns a flattened list of files from that directory

# TODO Call fgrep with the list previously created and another direcory name
# and print a list of filenames that were not found in the files contained in
# the directory, recursively

echo Hello Bash!
