#!/bin/bash

source ../functions

function testFlatListFiles() {
    flatListFilesFrom ./data/dirExample > flatList
    diff flatList ./data/flatListExample
    assertTrue 'Expected output differs.' $?
}

. ./shunit2-2.1.6/src/shunit2
