#!/bin/bash

. ../functions

function testFlatListFiles() {
    flatListFilesFrom ./data/dirExample > flatListOut
    diff flatListOut ./data/flatListExample
    assertTrue 'Expected output differs.' $?
}

. ./shunit2-2.1.6/src/shunit2
