#!/bin/bash

. ../functions

function testFlatListFiles() {
    flatListFilesFrom ./data/testFlatListFiles/dirExample > flatListOut
    diff flatListOut ./data/testFlatListFiles/flatListExample
    assertTrue 'Expected output differs.' $?
}

function testPrintNotFoundPattern() {
    pattern=file1.txt
    dir=./data/testFindNotMatchedPatternSubset
    actual=`findNotMatchedPatternSubset "$pattern" $dir`
    assertEquals file1.txt $actual
}

function testFindNotMatchedPatternSubset() {
    pattern=$'file1.txt\nfile2.jpg\nfile3.png'
    dir=./data/testFindNotMatchedPatternSubset
    actual=`findNotMatchedPatternSubset "$pattern" $dir`
    assertEquals file1.txt $actual
}

. ./shunit2-2.1.6/src/shunit2
